'use client'

import { useCallback, useState } from 'react'

interface PDFExportOptions {
  /** CSS selector or ref for the element to capture */
  filename?: string
  /** Title shown at top of PDF */
  title?: string
  /** Subtitle under the title */
  subtitle?: string
  /** Selector for the section(s) to capture. Defaults to '[data-pdf-section]' */
  sectionSelector?: string
}

/**
 * Hook to export a page section as a branded PDF.
 * Uses dynamic imports to avoid bundling html2canvas + jspdf for non-export users.
 */
export function usePDFExport() {
  const [isExporting, setIsExporting] = useState(false)

  const exportPDF = useCallback(async (
    containerRef: React.RefObject<HTMLElement | null>,
    options: PDFExportOptions = {}
  ) => {
    if (!containerRef.current || isExporting) return

    setIsExporting(true)

    try {
      // Dynamic imports — only loaded when user clicks export
      const [html2canvasModule, jsPDFModule] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ])
      const html2canvas = html2canvasModule.default
      const jsPDF = jsPDFModule.default

      const element = containerRef.current
      const {
        filename = 'battery-mom-report.pdf',
        title = 'battery.mom',
        subtitle,
      } = options

      // Capture the element as a canvas
      const canvas = await html2canvas(element, {
        scale: 2, // Retina quality
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        logging: false,
        // Ignore elements marked with data-pdf-ignore
        ignoreElements: (el) => el.hasAttribute('data-pdf-ignore'),
      })

      const imgData = canvas.toDataURL('image/png')
      const imgWidth = canvas.width
      const imgHeight = canvas.height

      // A4 dimensions in mm
      const pdfWidth = 210
      const pdfHeight = 297
      const margin = 12
      const contentWidth = pdfWidth - margin * 2

      // Header height
      const headerHeight = subtitle ? 22 : 16

      const doc = new jsPDF('p', 'mm', 'a4')

      // ── Header ──────────────────────────────────────────
      doc.setFillColor(16, 185, 129) // emerald-500
      doc.rect(0, 0, pdfWidth, headerHeight, 'F')

      doc.setTextColor(255, 255, 255)
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text(title, margin, subtitle ? 9 : 11)

      if (subtitle) {
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        doc.text(subtitle, margin, 17)
      }

      // ── Content ─────────────────────────────────────────
      const availableHeight = pdfHeight - headerHeight - margin - 10 // 10mm for footer
      const scale = contentWidth / imgWidth
      const scaledHeight = imgHeight * scale

      // If content fits on one page
      if (scaledHeight <= availableHeight) {
        doc.addImage(imgData, 'PNG', margin, headerHeight + 4, contentWidth, scaledHeight)
      } else {
        // Multi-page: slice the canvas into page-sized chunks
        const pageImgHeight = availableHeight / scale // in canvas pixels
        let srcY = 0
        let pageNum = 0

        while (srcY < imgHeight) {
          if (pageNum > 0) {
            doc.addPage()
          }

          const sliceHeight = Math.min(pageImgHeight, imgHeight - srcY)
          
          // Create a slice canvas
          const sliceCanvas = document.createElement('canvas')
          sliceCanvas.width = imgWidth
          sliceCanvas.height = sliceHeight
          const ctx = sliceCanvas.getContext('2d')
          if (ctx) {
            ctx.drawImage(
              canvas,
              0, srcY, imgWidth, sliceHeight,
              0, 0, imgWidth, sliceHeight
            )
          }

          const sliceData = sliceCanvas.toDataURL('image/png')
          const yOffset = pageNum === 0 ? headerHeight + 4 : margin
          const availH = pageNum === 0 ? availableHeight : pdfHeight - margin * 2 - 10
          const sliceScaledH = Math.min(sliceHeight * scale, availH)

          doc.addImage(sliceData, 'PNG', margin, yOffset, contentWidth, sliceScaledH)

          srcY += sliceHeight
          pageNum++
        }
      }

      // ── Footer on every page ────────────────────────────
      const totalPages = doc.getNumberOfPages()
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i)
        doc.setFontSize(7)
        doc.setTextColor(156, 163, 175) // gray-400
        doc.setFont('helvetica', 'normal')
        doc.text(
          `Generated by battery.mom · ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })} · Page ${i}/${totalPages}`,
          pdfWidth / 2,
          pdfHeight - 6,
          { align: 'center' }
        )
      }

      doc.save(filename)
    } catch (error) {
      console.error('PDF export failed:', error)
      alert('PDF export failed. Please try again.')
    } finally {
      setIsExporting(false)
    }
  }, [isExporting])

  return { exportPDF, isExporting }
}

/**
 * Reusable PDF export button component.
 */
export default function PDFExportButton({
  containerRef,
  options = {},
  className = '',
  children,
}: {
  containerRef: React.RefObject<HTMLElement | null>
  options?: PDFExportOptions
  className?: string
  children?: React.ReactNode
}) {
  const { exportPDF, isExporting } = usePDFExport()

  return (
    <button
      onClick={() => exportPDF(containerRef, options)}
      disabled={isExporting}
      className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg font-semibold text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed ${className}`}
      data-pdf-ignore
    >
      {isExporting ? (
        <>
          <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          Generating PDF…
        </>
      ) : (
        children || (
          <>
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </>
        )
      )}
    </button>
  )
}
